from __future__ import annotations

from swallow.sdk.errors import (
    IngestConfigError,
    IngestFacadeRegistryError,
    IngestProtocolError,
    IngestSandboxError,
    IngestSdkConfigError,
    IngestSdkError,
    IngestSdkInputError,
    IngestSdkJobNotFound,
    IngestSdkProtocolError,
    IngestTimeoutError,
    IngestTransportError,
    IngestUnsupportedCapability,
    IngestWaitTimeout,
)
from swallow.sdk.cli import CliIngestClient
from swallow.sdk.facade import IngestClient, create_ingest_client
from swallow.sdk.http import HttpIngestClient
from swallow.sdk.local import LocalIngestClient
from swallow.sdk.queue import QueueIngestClient
from swallow.sdk.models import (
    BackendCapabilities,
    BatchStatus,
    IngestBackend,
    IngestBackendSelection,
    IngestDocumentRef,
    IngestBatch,
    IngestBatchJob,
    IngestBatchResult,
    IngestError,
    IngestJob,
    IngestOutputs,
    IngestResult,
    IngestResultMeta,
    IngestStatus,
    IngestTextPayload,
    IngestWarning,
    ReturnContentMode,
    StorageMode,
)

__all__ = [
    "BackendCapabilities",
    "BatchStatus",
    "IngestBackend",
    "IngestBackendSelection",
    "IngestBatch",
    "IngestBatchJob",
    "IngestBatchResult",
    "IngestClient",
    "IngestConfigError",
    "IngestDocumentRef",
    "IngestError",
    "IngestFacadeRegistryError",
    "IngestJob",
    "IngestOutputs",
    "IngestProtocolError",
    "IngestResult",
    "IngestResultMeta",
    "IngestSandboxError",
    "IngestSdkConfigError",
    "IngestSdkError",
    "IngestSdkInputError",
    "IngestSdkJobNotFound",
    "IngestSdkProtocolError",
    "IngestStatus",
    "IngestTextPayload",
    "IngestTimeoutError",
    "IngestTransportError",
    "IngestUnsupportedCapability",
    "IngestWaitTimeout",
    "IngestWarning",
    "CliIngestClient",
    "HttpIngestClient",
    "LocalIngestClient",
    "QueueIngestClient",
    "ReturnContentMode",
    "StorageMode",
    "create_ingest_client",
]
